apiVersion: v1
kind: Service
metadata:
  labels:
    app: docsbox
  name: docsbox
  namespace: 
spec:
  ports:
  - port: 8001
    protocol: TCP
    targetPort: 8001
  selector:
    app: docsbox
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    type: docsbox-service
    version: "0.8.1"
  name: docsbox
  namespace: 
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: docsbox
  template:
    metadata:
      labels:
        app: docsbox
        type: docsbox-service
    spec:
      hostNetwork: true
      containers:
        - name: docsbox
          image: pgnomme/docsbox:v0.8.1
          ports:
            - containerPort: 8001
              protocol: TCP
          env:
            - name: REDIS_URL
              value: db-redis 
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
          volumeMounts:
            - name: pvc-redis
              mountPath: /home/docsbox/media
        - name: rqworker
          image: pgnomme/docsbox:v0.8.1
          command: ["rq", "worker", "-c", "docsbox.settings"]
          env:
            - name: REDIS_URL
              value: db-redis 
            - name: REDIS_PORT
              value: "6379"
          volumeMounts:
            - name: pvc-redis
              mountPath: /home/docsbox/media
        - name: rqscheduler
          image: pgnomme/docsbox:v0.8.1
          command: ["rqscheduler", "-H", db-redis, "-p", "6379", "-d", "0"]
          env:
            - name: REDIS_URL
              value: db-redis
            - name: REDIS_PORT
              value: "6379"
          volumeMounts:
            - name: pvc-redis
              mountPath: /home/docsbox/media
      volumes:
        - name: pvc-redis
          persistentVolumeClaim:
            claimName: pvc-redis
