apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-redis
  namespace: idbs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: redis-storage
  hostPath:
    path: /data/docsbox/redis
