apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-redis
  namespace: idbs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: redis-storage
  resources:
    requests:
      storage: 1Gi
